name: Build crDroid Kernel surya

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.setdate.outputs.DATE }}
    steps:
      - id: setdate
        run: |
          echo "DATE=$(TZ=Asia/Jakarta date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

  build_kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - name: Checkout Workflow & Local Configs
      uses: actions/checkout@v4

    - name: Set environment
      run: |
        echo "DATE=${{ needs.prepare.outputs.DATE }}" >> $GITHUB_ENV
        echo "ARTIFACT=$GITHUB_WORKSPACE/artifact" >> $GITHUB_ENV
        echo "KERNEL_URL=https://github.com/crdroidandroid/android_kernel_xiaomi_surya.git" >> $GITHUB_ENV
        echo "KERNEL_BRANCH=16.0" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y device-tree-compiler bc build-essential flex bison libssl-dev libelf-dev clang lld wget python3 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
        mkdir -p ${{ env.ARTIFACT }}

    - name: Fetch crDroid Kernel Source
      run: |
        git clone --depth=1 -b ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_URL }} kernel_workspace

    - name: Apply Droidspaces Patches
      run: |
        cd kernel_workspace
        # Download patch non-GKI
        URLS=(
          "https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/01.fix_kernel_panic_in_xt_qtaguid.patch"
          "https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch"
        )
        for url in "${URLS[@]}"; do
          wget -q "$url"
        done
        # Terapkan patch dengan p1
        for p in *.patch; do
          echo "Applying $p..."
          patch -p1 --forward --batch < "$p" || echo "Gagal/Skip $p"
        done

    - name: Setup Droidspaces Configs
      run: |
        # Salin config dari folder configs/ di repo kamu ke source kernel
        mkdir -p kernel_workspace/arch/arm64/configs/
        cp configs/droidspaces.config kernel_workspace/arch/arm64/configs/
        cp configs/droidspaces-additional.config kernel_workspace/arch/arm64/configs/ || true

    - name: Patch build.sh
      run: |
        chmod +x patch/buildpatchCR.sh
        # build.sh crDroid biasanya ada di root source kernel
        chmod +x kernel_workspace/build.sh
        ./patch/buildpatchCR.sh kernel_workspace/build.sh

    - name: Building
      run: |
        cd kernel_workspace
        ./build.sh

    - name: Move ZIP to Artifact
      run: |
        mv kernel_workspace/*.zip ${{ env.ARTIFACT }}/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: crDroid-surya-${{ env.DATE }}
        path: ${{ env.ARTIFACT }}/*
